apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: api-jwt
  namespace: shop
spec:
  selector:
    matchLabels:
      app: api
  jwtRules:
    - issuer: https://wp.pl/
      audiences: [shop-api]
      jwksUri: https://wp.pl/.well-known/jwks.json
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: api-jwt-access
  namespace: shop
spec:
  selector:
    matchLabels:
      app: api
  action: ALLOW
  rules:
    - from:
        - source:
            requestPrincipals: ["*"]
