apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: gateway-blue
spec:
  selector:
    istio: gateway-blue
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts: [wp.pl]
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts: [wp.pl]
    tls:
      mode: SIMPLE
      credentialName: wp-pl-tls
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: gateway-blue
spec:
  hosts: [wp.pl]
  gateways: [gateway-blue]
  exportTo: [.]
  http:
  - route:
    - destination:
        host: playground-trouble.prod-playground-trouble.svc.cluster.local
        port:
          number: 80
