apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: app
  annotations:
    proxy.istio.io/config: |
      terminationDrainDuration: 30s
spec:
  terminationGracePeriodSeconds: 45
  containers: [{name: app, image: 'nginxinc/nginx-unprivileged:1.29-alpine3.22', ports: [{containerPort: 8080}]}]
