apiVersion: v1
kind: Pod
metadata:
  name: app
  namespace: shop
  annotations:
    proxy.istio.io/config: |
      holdApplicationUntilProxyStarts: true
spec:
  containers: [{name: app, image: 'curlimages/curl:8.16.0', command: [sh, -c, 'curl --fail --max-time 10 http://wp.pl; sleep 3600']}]
