apiVersion: v1
kind: Pod
metadata:
  name: app
  annotations:
    proxy.istio.io/config: |
      proxyStatsMatcher:
        inclusionRegexps: [.*upstream_rq_retry.*, .*upstream_rq_pending_overflow.*, .*upstream_cx_active.*]
spec:
  containers:
  - name: app
    image: curlimages/curl:8.16.0
    command: [sh, -c, sleep 3600]
