apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: default
spec:
  hosts: [wp.pl]
  location: MESH_EXTERNAL
  resolution: DNS
  ports: [{number: 443, name: https, protocol: TLS}]
  endpoints: [{address: backend.wp.pl}]
  exportTo: [.]
