apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: default
spec:
  hosts: [wp.pl]
  location: MESH_EXTERNAL
  resolution: STATIC
  ports:
  - number: 443
    name: https
    protocol: TLS
  endpoints:
  - address: 8.8.8.8
  exportTo: [.]
