apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cds-reject.yaml
- churn.yaml
- config-delivery.yaml
- empty.yaml
- excluded.yaml
- gateway-overflow.yaml
- gateway-pressure.yaml
- gateway-reject.yaml
- gateway-tls.yaml
- gateway-unhealthy.yaml
- gateway-warming.yaml
- oom.yaml
- overflow.yaml
- reset.yaml
- retry.yaml
- tcp-conflict.yaml
- timeout.yaml
- unready.yaml
- xds-block.yaml
